name: litterbox-driver-v19
packageKey: litterbox-driver-v19
permissions:
  zigbee: {}
description: "LitterBox.v1 Smart Pet Toilet Monitor"
vendorSupportInformation: https://github.com/reastykim/litterbox
