name: litterbox-driver-v14
packageKey: litterbox-driver-v14
permissions:
  zigbee: {}
description: SmartThings Edge Driver for LitterBox.v1 Cat Litter Box Monitor
vendorSupportInformation: https://github.com/reasty/litterbox
