name: litterbox-driver-v20
packageKey: litterbox-driver-v20
permissions:
  zigbee: {}
description: "LitterBox.v1 Smart Pet Toilet Monitor"
vendorSupportInformation: https://github.com/reastykim/litterbox
